- ape_infura/providers.py
- setup.py
Upgrade to Web3Provider
Delete everything and inherit from the base class
Deploy a contract! (that is what I did)
> feat: upgrade to latest ape

- .github/PULL_REQUEST_TEMPLATE.md
- .pre-commit-config.yaml
- README.md
- pyproject.toml
- setup.py
Upgrades ape
Adds missed template upgrades
> chore: upgrade dependencies

- .github/PULL_REQUEST_TEMPLATE.md
- README.md
- setup.py
> chore: prepare for beta release

- ape_infura/providers.py
- setup.py
Handle changes from ApeWorX/ape#372
NOTE: The build will fail until we release. I am just opening this PR so we can do swift-releases afterward.
> chore: handle ape breaking changes regarding receipt status check

- setup.py
> chore: upgrade missing lint packages from template

- README.md
- ape_infura/providers.py
- setup.py
> refactor: upgrade to 0.1.0

- .pre-commit-config.yaml
- pyproject.toml
- setup.py
> chore: accept updates from template

- setup.py
> chore: upgrade eth-ape version

- setup.py
update pins for ape 0.4.0 
update setup.py
github checks
> chore: update pins for ape 0.4.0

- .github/ISSUE_TEMPLATE/bug.md
- .github/workflows/test.yaml
- .pre-commit-config.yaml
- CONTRIBUTING.md
- setup.py
- tests/conftest.py
> chore: update setup pinnings

- .github/workflows/test.yaml
> fix: test setup

- .pre-commit-config.yaml
- CONTRIBUTING.md
- README.md
Updates README to match alchemy plugin be showing how to set API key
> docs: update usage example to include API key

- .github/workflows/test.yaml
- .pre-commit-config.yaml
- README.md
- ape_infura/providers.py
- pyproject.toml
- setup.py
- tests/conftest.py
- tests/test_provider.py
Remaking the pull request off a branch to access env vars.
> chore: bump 0.5.0

- README.md
- ape_infura/__init__.py
- ape_infura/providers.py
- setup.py
- tests/test_provider.py
Remove kovan, ropsten, and rinkeby
> fix: handle network deprecations

- .pre-commit-config.yaml
- ape_infura/__init__.py
- ape_infura/provider.py
- setup.py
- tests/test_provider.py
> fix: add poa where needed

- .github/ISSUE_TEMPLATE/bug.md
- .github/ISSUE_TEMPLATE/feature.md
- .github/ISSUE_TEMPLATE/work-item.md
- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/commit.yaml
- .github/workflows/prtitle.yaml
- .github/workflows/publish.yaml
- .github/workflows/test.yaml
- .gitignore
- .mdformat.toml
- .pre-commit-config.yaml
- README.md
- ape_infura/provider.py
- pyproject.toml
- setup.py
> chore: upgrade to 0.6

- .github/workflows/commit.yaml
- .github/workflows/prtitle.yaml
- .github/workflows/publish.yaml
- .github/workflows/test.yaml
- .pre-commit-config.yaml
- README.md
- pyproject.toml
- setup.py
> feat: python 3.11 support [APE-1067]

- ape_infura/__init__.py
requires: https://github.com/ApeWorX/ape-infura/pull/68
> feat: support arbitrum sepolia testnet [APE-1493]

- ape_infura/__init__.py
requires: https://github.com/ApeWorX/ape-optimism/pull/19
> feat: support optimism sepolia testnet [APE-1489]

- .mdformat.toml
- .pre-commit-config.yaml
- ape_infura/__init__.py
- ape_infura/provider.py
- pyproject.toml
- setup.py
> feat!: upgrade to ape 0.7

- .github/workflows/draft.yaml
> chore: fix drafter permissions

- ape_infura/__init__.py
- ape_infura/provider.py
fixes: #75 
Added "amoy" as a valid network, and added amoy's chain id for poa support.
> feat: add support for Polygon Amoy

- .github/workflows/test.yaml
- README.md
- ape_infura/provider.py
- pyproject.toml
- setup.py
> feat!: Update to Ape 0.8

- .pre-commit-config.yaml
- ape_infura/__init__.py
- ape_infura/utils.py
- setup.cfg
- setup.py
Before:
```
In [1]: %time import ape_infura
CPU times: user 1.09 s, sys: 149 ms, total: 1.24 s
Wall time: 1.25 s
```
After:
```
In [1]: %time import ape_infura
CPU times: user 7.45 ms, sys: 2.55 ms, total: 10 ms
Wall time: 8.9 ms
```
> perf: plugin load time

- README.md
> docs: rebrand to Metamask Developer portal
