ApeWorX/ape-infura

- .github/workflows/test.yaml
- ape_infura/providers.py
- setup.py
- tests/test_provider.py
fixes: #1 
added `chain_id` to provider api
`ape console --network ethereum:ropsten:infura` works again
> fix: added provider chain_id

- ape_infura/providers.py
- pyproject.toml
- setup.py
Same thing we had to do for `ape-geth` (fka as `ape-http`) (https://github.com/ApeWorX/ape/pull/190) but for here
Noticed I couldn't make calls with infura
Looked up how I fixed it in the ape PR
Applied fix
Tested, it worked!
Create a simple contract like this:
```solidity
// SPDX-License-Identifier: MIT
pragma solidity ^0.6.0;
contract MyNumber {
int public number = 42;
}
```
Call it in a script like this:
```python
from ape import accounts
from ape import project
def main():
test_account = accounts.load("hardhat_0")
contract_type = project.MyNumber
contract = test_account.deploy(contract_type)
my_num = contract.number(sender=test_account)
print(my_num)
```
Use Infura:
```bash
ape run get_number --network ethereum:rinkeby:infura
```
It should print out `42`.
> fix: issue preventing Eth calls from working

- ape_infura/providers.py
- pyproject.toml
- setup.py
fixes: #3 
Also dust it off in preparation of some custom error handling I want to add eventually related to `TransactionError` and reverts.
Raise a custom error that is a `ProviderError` when the env vars are not set. Displays the possible env vars to set in the error message.
```bash
unset WEB3_INFURA_PROJECT_ID
ape run script --network ethereum:rinkeby:infura
```
> fix: raise error when Infura project Id is not set

- ape_infura/providers.py
Make `Infura` declared as an `UpstreamProvider` so it can be used in `ape-hardhat` `MainnetForkProvider`
Import the mixin class
Set the URI in the `__post_init__`
Return the URI in the API method
> feat: make Infura an upstream provider

- ape_infura/provider.py
- tests/test_provider.py
Noticed errors when forking Goerli.
It is because we need the first block hash.
> fix: add PoA middleware to Ethereum:goerli since it started as PoA

- ape_infura/__init__.py
- setup.py
- tests/test_provider.py
Add the sepolia testnet to the etherum ecosystem, following https://github.com/ApeWorX/ape/pull/1331
Add references to it where it seemed suitable.
```sh
ape networks list
ape console --network ethereum:sepolia:infura
```
> feat: add sepolia network [APE-696]

- README.md
- ape_infura/__init__.py
- ape_infura/provider.py
- setup.py
- tests/test_provider.py
Add the Linea network (Mainnet and goerli testnet) support to the plugin , 
* add linea network information to plugin
* add new test in test.
```
pip install ape-linea
ape networks list
ape console --network linea:goerli:infura
ape console --network linea:mainnet:infura
```
> feat: add linea network support [APE-1170]

- .pre-commit-config.yaml
- CONTRIBUTING.md
- README.md
- ape_infura/provider.py
- pyproject.toml
- setup.py
- tests/conftest.py
- tests/test_provider.py
> feat: add support for `.http_uri` and `.ws_uri` in ProviderAPI v0.6.19 [APE-1381]

- ape_infura/provider.py
- tests/test_provider.py
Noticed that infura only supports 3 networks for websockets: https://docs.infura.io/learn/websockets#supported-networks
> fix: limit to websocket capable ecosystems [APE-1492]

- ape_infura/provider.py
> feat: add websocket support for arbitrum and optimism

- ape_infura/__init__.py
fixes: #73 
BREAKING CHANGE: "goerli" no longer a valid value for arbitrum or optimism.
Removed "goerli" entries for arbitrum and optimism. The tests fail otherwise.
> refactor!: remove goerli network from arbitrum and optimism

- README.md
- ape_infura/__init__.py
- ape_infura/provider.py
https://blog.ethereum.org/2023/11/30/goerli-lts-update
https://www.alchemy.com/blog/goerli-faucet-deprecation
Goerli support on all networks is ending soon:
- February 16th - [Base Goerli](https://www.alchemy.com/blog/base-goerli-testnet-deprecation)
- March 7th - [Optimism Goerli](https://www.alchemy.com/blog/optimism-goerli-testnet-deprecation)
- March 18th - [Arbitrum Goerli](https://www.alchemy.com/blog/arbitrum-goerli-testnet-deprecation)
- April 1st - [Ethereum Goerli](https://www.alchemy.com/blog/ethereum-goerli-testnet-deprecation)
- April 6th - [Polygon zkEVM Goerli](https://www.alchemy.com/blog/polygon-zkevm-cardona-is-live)
- April 11th - [Starknet Goerli](https://www.alchemy.com/blog/starknet-sepolia-is-live)
- April 13th - [Polygon …
> refactor: remove goerli

- .github/workflows/test.yaml
- README.md
- ape_infura/provider.py
- setup.py
- tests/test_provider.py
fixes: #87
- Added option to load API Keys in random order. Have to define API keys as an array of items. 
```sh
export WEB3_INFURA_PROJECT_ID="cxxxxxxxxxxxxx, f4xxxxxxxxxxxxx, 6xxxxxxxxxxxxx, axxxxxxxxxxxxx"
set -gx WEB3_INFURA_PROJECT_IDS "cxxxxxxxxxxxxx, f4xxxxxxxxxxxxx, 6xxxxxxxxxxxxx, axxxxxxxxxxxxx"
```
- Trust me bro ;)
> feat: added option to load multiple api keys selected at random order

- ape_infura/provider.py
- tests/test_provider.py
tests were failing from the merging of this PR: https://github.com/ApeWorX/ape-infura/pull/88
The issues were from API keys not resetting.
instead of "load_api_keys", make api keys a cached property and have it get deleted on disconnect
also in the tests, i had to reset the env patch
> test: issues with multiple api keys

- .pre-commit-config.yaml
- ape_infura/__init__.py
- setup.py
> chore: adds back in __all__ to library and adds flake8 and mdformat deps

- ape_infura/provider.py
- ape_infura/utils.py
- tests/test_provider.py
sets up dynamic poa middleware check
fixes: #61
> feat: add dynamic middleware check

- README.md
- ape_infura/provider.py
- tests/conftest.py
- tests/test_provider.py
This PR adds support for using Infura in a mode that requires API secret
https://docs.metamask.io/developer-tools/dashboard/how-to/secure-an-api/api-key-secret/#enable-the-api-key-secret-for-requests
> feat: add support for API secret

- pyproject.toml
- setup.py
- tests/test_provider.py
> fix: release dist naming fix

- .github/workflows/docs.yaml
- CONTRIBUTING.md
- ape_infura/provider.py
- docs/conf.py
- docs/index.rst
- docs/userguides/quickstart.md
- setup.py
- tests/test_provider.py
> feat: support web3.py dependencies

- ape_infura/provider.py
tests failing because of 429 on chain ID check for the PoA middleware.
This PR adds a rate limiting helper that can be used anymore but is used on chain ID for now, for the sake of passing tests and being able to connect to a bunch of chains w/o erroring
> feat: handle 429 / rate-limiting on chain ID request
